"""empty message

Revision ID: 1e025a28d322
Revises: d94e86ea0bde
Create Date: 2023-12-16 18:37:58.868783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e025a28d322'
down_revision = 'd94e86ea0bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planets_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('favorite_people_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_people_text')
        batch_op.drop_column('favorite_planets_text')

    # ### end Alembic commands ###
