"""empty message

Revision ID: 213af5487b73
Revises: 1e025a28d322
Create Date: 2023-12-16 18:38:46.466840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213af5487b73'
down_revision = '1e025a28d322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_favorite_planets', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_favorite_people', sa.Text(), nullable=True))
        batch_op.drop_column('favorite_people_text')
        batch_op.drop_column('favorite_planets_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planets_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('favorite_people_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('user_favorite_people')
        batch_op.drop_column('user_favorite_planets')

    # ### end Alembic commands ###
