"""empty message

Revision ID: 56a055278da6
Revises: 09b46ca59813
Create Date: 2023-12-13 21:44:03.326987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a055278da6'
down_revision = '09b46ca59813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('home_planet', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('home_planet')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
