"""empty message

Revision ID: 56e3a78b0bc1
Revises: 60decc569468
Create Date: 2023-12-13 21:39:57.119256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e3a78b0bc1'
down_revision = '60decc569468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('people_nombre_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('planeta_natal')
        batch_op.drop_column('nombre')
        batch_op.drop_column('especie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especie', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planeta_natal', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('people_nombre_key', ['nombre'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
