"""empty message

Revision ID: 71f64eaa3c21
Revises: 213af5487b73
Create Date: 2023-12-16 18:41:08.182192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f64eaa3c21'
down_revision = '213af5487b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_favorite_people')
        batch_op.drop_column('user_favorite_planets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_favorite_planets', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_favorite_people', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
