"""empty message

Revision ID: 9e3e52bd8dee
Revises: 022a82977c4b
Create Date: 2023-12-15 19:25:57.698649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3e52bd8dee'
down_revision = '022a82977c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_name_key', ['name'])

    # ### end Alembic commands ###
