"""empty message

Revision ID: cfee60511500
Revises: 669afc51beb5
Create Date: 2023-12-13 21:56:25.227915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfee60511500'
down_revision = '669afc51beb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_terrain', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=120), nullable=False))
        batch_op.drop_column('gender')
        batch_op.drop_column('height')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('home_planet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_planet', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('climate')
        batch_op.drop_column('diameter')
        batch_op.drop_column('population')
        batch_op.drop_column('type_of_terrain')

    # ### end Alembic commands ###
